import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { openai } from '@/lib/openai';

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(req: NextRequest) {
    try {
        const { projectId } = await req.json();
        if (!projectId) return NextResponse.json({ error: 'Missing projectId' }, { status: 400 });

        // Fetch memories
        const { data: memories } = await supabase
            .from('memory_chunks')
            .select('content, source_type, source_label, importance_score, created_at')
            .eq('project_id', projectId)
            .order('importance_score', { ascending: false })
            .limit(40);

        // Fetch concepts
        const { data: concepts } = await supabase
            .from('concepts')
            .select('label, cluster, weight')
            .eq('project_id', projectId)
            .order('weight', { ascending: false })
            .limit(20);

        // Fetch sessions
        const { data: sessions } = await supabase
            .from('sessions')
            .select('title, summary, open_questions, created_at')
            .eq('project_id', projectId)
            .order('created_at', { ascending: false })
            .limit(10);

        // Fetch project info
        const { data: project } = await supabase
            .from('projects')
            .select('name, description')
            .eq('id', projectId)
            .single();

        if (!memories?.length) {
            return NextResponse.json({
                error: 'Not enough research data to generate a brief. Complete at least one research session first.'
            }, { status: 422 });
        }

        // Build context for LLM
        const memoryContext = (memories || []).slice(0, 25)
            .map((m, i) => `[${i + 1}] (${m.source_type} — ${m.source_label})\n${m.content.slice(0, 300)}`)
            .join('\n\n');

        const conceptList = (concepts || [])
            .map(c => `${c.label} (${c.cluster}, weight: ${c.weight})`)
            .join(', ');

        const sessionSummaries = (sessions || [])
            .filter(s => s.summary)
            .map(s => `Session: ${s.title}\n${s.summary}`)
            .join('\n\n');

        const openQuestions = (sessions || [])
            .flatMap(s => s.open_questions || [])
            .filter(Boolean)
            .slice(0, 8);

        const prompt = `You are a world-class research synthesis AI. You have access to a researcher's complete knowledge base on the project "${project?.name || 'Research Project'}".

PROJECT: ${project?.name}
DESCRIPTION: ${project?.description || 'N/A'}

KEY CONCEPTS IDENTIFIED: ${conceptList || 'None yet'}

SESSION HISTORY:
${sessionSummaries || 'No session summaries available.'}

RESEARCH MEMORY (${memories.length} entries):
${memoryContext}

OPEN QUESTIONS FROM SESSIONS:
${openQuestions.map((q, i) => `${i + 1}. ${q}`).join('\n') || 'None recorded.'}

Write a comprehensive, publication-quality research brief. Use the following structure exactly:

# Research Brief: ${project?.name || 'Research Project'}

## Executive Summary
(2-3 sentences capturing the core thrust of this body of research)

## Key Findings
(4-6 numbered findings, each 1-2 sentences, grounded in the research memory above)

## Core Concepts & Relationships
(Describe the 3-4 most important concepts and how they interconnect)

## Areas of Agreement
(What does the research consistently confirm?)

## Active Debates & Contradictions  
(Where does the evidence conflict or remain unsettled?)

## Critical Knowledge Gaps
(What important questions remain unanswered in this research body?)

## Recommended Next Research Steps
(3-5 specific, actionable steps the researcher should take next)

## Open Questions
(List the open questions that have emerged from sessions)

---
*Generated by CLARIBB Research Intelligence · ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}*
*Based on ${memories.length} memory entries across ${sessions?.length || 0} research sessions*`;

        const res = await openai.chat.completions.create({
            model: 'llama-3.3-70b-versatile',
            messages: [
                { role: 'system', content: 'You are a research synthesis expert. Write in a clear, precise, academic-adjacent style. Be concrete and specific — cite concepts and ideas from the research, not generic advice.' },
                { role: 'user', content: prompt },
            ],
            max_tokens: 1500,
            temperature: 0.5,
        });

        const brief = res.choices[0]?.message?.content || '';
        if (!brief) return NextResponse.json({ error: 'Failed to generate brief' }, { status: 500 });

        return NextResponse.json({
            brief,
            stats: {
                memories: memories.length,
                concepts: concepts?.length || 0,
                sessions: sessions?.length || 0,
            },
            generatedAt: new Date().toISOString(),
        });
    } catch (err) {
        console.error('[/api/brief] Error:', err);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
